version: '3'

services:
  front:
    build:
      context: .
    image: jongleur_front:0.1.4
    ports:
      - 8088:80
    depends_on:
      - back

  back:
    build:
      context: ./jongleur_back
    image: jongleur_back:0.1.3
    environment:
      ROCKET_ENV: production
      MONGO_DB: jongleur
      MONGO_ENDPOINT: mongodb://db:27017/
      REDIS_ENDPOINT: redis://session:6379
    depends_on:
      - session
      - db

  session:
    image: redis:3.2.10-alpine

  db:
    image: mongo:3.4.8
