version: '3'

services:
  front:
    build: .
    image: jongleur_front:0.1.0
    ports:
      - 8080:80
    depends_on:
      - back

  back:
    build: ./jongleur_back
    image: jongleur_back:0.1.0
    environment:
      ROCKET_ENV: production
      JL_MONGO_DB: jongleur
      JL_MONGO_ENDPOINT: mongodb://mongo/
      JL_REDIS_ENDPOINT: redis://redis
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:3.2.10-alpine

  mongo:
    image: mongo:3.4.8
